//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.myDB
{
    using System;
    using System.Collections.Generic;

    public partial class Task
    {
        public string login { get; set; }
        public System.DateTime compleateDate { get; set; }
        public int priority { get; set; }
        public string taskText { get; set; }
        public int taskNumber { get; set; }
        public string category { get; set; }

        public virtual User User { get; set; }
    }
}